import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import User from "./models/User.js";
import dotenv from "dotenv";

dotenv.config();

// Real male and female user data
const usersData = [
  {
    name: "Liam Smith",
    age: 29,
    bio: "Musician 🎸. Always up for a jam session or hitting the beach 🌊. Looking for a partner in crime!",
    email: "liam.smith@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    name: "James Williams",
    age: 31,
    bio: "Software engineer 💻. I enjoy coding, gaming 🎮, and good conversation. Let's grab a coffee ☕ sometime.",
    email: "james.williams@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    name: "Noah Johnson",
    age: 25,
    bio: "Adventure junkie 🌍. Always planning my next trip. Let's explore together!",
    email: "noah.johnson@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/50.jpg",
  },
  {
    name: "William Brown",
    age: 27,
    bio: "Fitness trainer 💪. Love working out and helping others achieve their fitness goals.",
    email: "william.brown@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/55.jpg",
  },
  {
    name: "Elijah Davis",
    age: 30,
    bio: "Tech geek 🚀. Into gadgets, coding, and a good sci-fi movie. Swipe right if you're a fellow nerd!",
    email: "elijah.davis@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/56.jpg",
  },
  {
    name: "Oliver Martinez",
    age: 26,
    bio: "Dog lover 🐶. My weekends are all about hiking with my pup and finding the best food spots.",
    email: "oliver.martinez@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    name: "Lucas Miller",
    age: 23,
    bio: "College student 📚. Music and basketball are life. Swipe right if you want to shoot some hoops.",
    email: "lucas.miller@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    name: "Mason Wilson",
    age: 32,
    bio: "Aspiring chef 🍳. I love cooking up new recipes and trying different cuisines. Let's cook together!",
    email: "mason.wilson@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    name: "Ethan Taylor",
    age: 28,
    bio: "Traveler 🌍. I've been to 20 countries and counting. Looking for someone to explore the world with.",
    email: "ethan.taylor@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/31.jpg",
  },
  {
    name: "Jacob Anderson",
    age: 24,
    bio: "Avid reader 📖. Always looking for book recommendations. Let's discuss your latest read.",
    email: "jacob.anderson@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/43.jpg",
  },
  {
    name: "Alexander Thomas",
    age: 26,
    bio: "Entrepreneur 🚀. Building my own startup and looking for someone who appreciates ambition.",
    email: "alexander.thomas@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    name: "Michael Jackson",
    age: 27,
    bio: "Fitness enthusiast 🏋️‍♂️. Gym time is the best time. Looking for someone who shares the grind.",
    email: "michael.jackson@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    name: "Daniel White",
    age: 30,
    bio: "Gamer 🎮. Late-night gaming sessions and chill vibes. Let's team up for a match!",
    email: "daniel.white@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    name: "Sebastian Harris",
    age: 22,
    bio: "Nature lover 🌿. Enjoy hiking, camping, and the outdoors. Swipe right if you're a nature enthusiast.",
    email: "sebastian.harris@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    name: "Aiden Lewis",
    age: 29,
    bio: "Photographer 📸. Capturing moments one click at a time. Let's create memories together.",
    email: "aiden.lewis@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    name: "Matthew Clark",
    age: 34,
    bio: "Business consultant 💼. Always thinking about my next project. Let's talk shop over coffee!",
    email: "matthew.clark@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Henry Robinson",
    age: 25,
    bio: "Mechanical engineer ⚙️. Love tinkering with gadgets and solving problems. Swipe right for some geek talk.",
    email: "henry.robinson@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
  },
  {
    name: "Samuel Walker",
    age: 28,
    bio: "Marketing guru 📈. Into branding, social media, and all things creative. Looking for someone to inspire me.",
    email: "samuel.walker@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    name: "David Young",
    age: 33,
    bio: "Foodie 🍣. Love trying new restaurants and dishes. Swipe right if you’re a fellow food lover!",
    email: "david.young@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    name: "Joseph Scott",
    age: 24,
    bio: "Film buff 🎬. Always on the lookout for the next indie film. Let's catch a movie together!",
    email: "joseph.scott@example.com",
    gender: "male",
    genderPreference: "female",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    name: "Sophia Carter",
    age: 26,
    bio: "Love hiking, yoga, and finding new coffee shops ☕. Swipe right if you're up for an adventure!",
    email: "sophia.carter@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    name: "Emma Davis",
    age: 30,
    bio: "Dog mom 🐾, bookworm, and lover of all things tech. Looking for a fun and intellectual connection.",
    email: "emma.davis@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    name: "Olivia Johnson",
    age: 27,
    bio: "Artist 🎨. I paint, sketch, and create. Looking for someone who loves art and creativity.",
    email: "olivia.johnson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    name: "Ava Williams",
    age: 24,
    bio: "Travel enthusiast 🌍. I've been to 10 countries so far, and I'm always planning my next trip.",
    email: "ava.williams@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    name: "Isabella Martinez",
    age: 28,
    bio: "Yoga instructor 🧘‍♀️. I believe in living a balanced and healthy lifestyle. Let's flow together.",
    email: "isabella.martinez@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    name: "Mia Thompson",
    age: 25,
    bio: "Food lover 🍣. If you're into trying new dishes and exploring restaurants, we might just be a match!",
    email: "mia.thompson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/56.jpg",
  },
  {
    name: "Amelia Anderson",
    age: 22,
    bio: "Book lover 📖. Always reading something new. Let's swap recommendations and stories!",
    email: "amelia.anderson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/41.jpg",
  },
  {
    name: "Harper Wilson",
    age: 29,
    bio: "Dancer 💃. I love expressing myself through movement. Let's dance through life together.",
    email: "harper.wilson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
  },
  {
    name: "Evelyn Taylor",
    age: 26,
    bio: "Nature enthusiast 🌿. Enjoys camping, hiking, and being outdoors. Looking for an adventure buddy.",
    email: "evelyn.taylor@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
  },
  {
    name: "Ella Clark",
    age: 23,
    bio: "Film and photography lover 🎬📸. Let's shoot some photos or watch some movies together!",
    email: "ella.clark@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/38.jpg",
  },
  {
    name: "Abigail Moore",
    age: 32,
    bio: "Fitness coach 🏋️‍♀️. Helping people reach their goals is my passion. Let's motivate each other.",
    email: "abigail.moore@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Sofia Jackson",
    age: 28,
    bio: "Tech startup founder 🚀. I'm all about innovation and creativity. Let's brainstorm ideas over coffee.",
    email: "sofia.jackson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    name: "Camila Harris",
    age: 24,
    bio: "Aspiring chef 🍳. I love cooking and experimenting with new recipes. Let's cook together!",
    email: "camila.harris@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    name: "Gianna Lewis",
    age: 26,
    bio: "Marketing specialist 📈. I'm into all things creative and innovative. Looking for someone equally passionate.",
    email: "gianna.lewis@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/49.jpg",
  },
  {
    name: "Charlotte Young",
    age: 27,
    bio: "Musician 🎶. My guitar is my best friend. Let's make some music together!",
    email: "charlotte.young@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    name: "Aria Hernandez",
    age: 24,
    bio: "Designer ✏️. I love working on new creative projects. Let's inspire each other!",
    email: "aria.hernandez@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    name: "Scarlett Robinson",
    age: 29,
    bio: "Entrepreneur 💼. Building my own brand and looking for someone who's as ambitious as me.",
    email: "scarlett.robinson@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    name: "Penelope Walker",
    age: 31,
    bio: "Traveler 🌍. I've been to 15 countries and love experiencing new cultures. Let's go on an adventure.",
    email: "penelope.walker@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    name: "Violet Scott",
    age: 30,
    bio: "Fashion designer 👗. My passion is creating unique styles. Swipe right if you're into fashion!",
    email: "violet.scott@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/31.jpg",
  },
  {
    name: "Grace King",
    age: 22,
    bio: "College student 🎓. Balancing study, work, and fun. Let's grab a coffee and chat about life.",
    email: "grace.king@example.com",
    gender: "female",
    genderPreference: "male",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
];

const formattedUsers = usersData.map((user) => ({
  ...user,
  password: bcrypt.hashSync("123456", 10),
}));

const seedUsers = async () => {
  try {
    await mongoose.connect("mongodb://localhost:27017/tinder");

    await User.deleteMany({});

    await User.insertMany(formattedUsers);

    console.log("Database seeded successfully with real user data.");
  } catch (error) {
    console.error("Error seeding database:", error);
  } finally {
    mongoose.disconnect();
  }
};

seedUsers();
